name: barberia
description: A barbershop booking app.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  barberia_ui:
    git:
      url: https://github.com/kevinkwee/barberia_ui.git
      ref: main
  go_router: ^5.1.7
  get_it: ^7.2.0
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  geoflutterfire2: ^2.3.14
  fpdart: ^0.3.0
  cloud_firestore: ^4.1.0
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  another_flushbar: ^1.12.29
  rxdart: ^0.27.7
  firebase_storage: ^11.0.6
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  path: ^1.8.2
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  latlong2: ^0.8.1
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  flutter_map: ^3.0.0
  flutter_map_location_marker: ^5.0.0+1
  timeago: ^3.3.0
  url_launcher: ^6.1.7
  share_plus: ^6.3.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
